name: 🚀 Doxygen

on:
  workflow_dispatch:

jobs:
  run:
    name: 🚀 Doxygen
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🚀 Doxygen
        shell: bash
        run: |
          sudo apt install doxygen
          doxygen -g
          doxygen
          
